version: "3"
services:
  api:
    container_name: api-guide-container
    image: node:13
    working_dir: /usr/src/guide-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/guide-node-api/dist/
      - ./package.json:/usr/src/guide-node-api/package.json
    ports:
      - "3000:3000"
      - "9222:9222"
